# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: 1. Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
  
    - name: 2. Download Notes.jar
      run: |
        echo "2.1) pwd"
        pwd 
        echo "2.2) curl"
        curl -L -O https://domino-1.dmytro.cloud/jar.nsf/0/file/$FILE/Notes.zip
        echo "2.3) unzip"
        unzip Notes.zip
        echo "2.4) ls -lh"
        ls -lh 

    - name: 3. Add Notes.jar to local repository
      run: |
        echo "ls -lh"
        ls -lh 
        echo "adding Notes.jar to local maven storage"
        mvn install:install-file -Dfile="Notes.jar" -DgroupId=lotus.notes -DartifactId=notes -Dversion=10.0 -Dpackaging=jar 

    - name: Build with Maven
      run: mvn package

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
