# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: 1. Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: 2. Download Notes.jar
      run: |
        curl -O https://domino-1.dmytro.cloud/jar.nsf/0/file/$FILE/Notes.jar
        ls -a
    - name: 3. Add Notes.jar to local repository
        mvn install:install-file -Dfile="Notes.jar" -DgroupId=lotus.notes -DartifactId=notes -Dversion=10.0 -Dpackaging=jar
    - name: 4. Build with Maven
      run: mvn -B package --file pom.xml
